# Generated by Django 5.1.7 on 2025-05-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0002_alter_application_unique_together_application_resume_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="projectid",
            field=models.ForeignKey(
                db_column="projectid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="portal.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("studentid", "projectid"),
                name="unique_student_project_application",
            ),
        ),
    ]
